version: "3.7"

services:
  school_db:
    image: postgres
    container_name: school_db
    environment:
      - POSTGRES_DB=school_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
