version: "3.7"

services:
  school_db:
    image: postgres
    container_name: school_db
    environment:
      - POSTGRES_DB=school_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - network-django-puc

  django-app:
    build:
      context: .
    container_name: django-app
    ports:
      - 8000:8000
    depends_on:
      - school_db
    networks:
      - network-django-puc

networks:
  network-django-puc:
    driver: bridge
