# Generated by Django 5.0.4 on 2024-04-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_code', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('date_of_birth', models.DateField()),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(null=True)),
                ('address_street', models.CharField(max_length=80)),
                ('address_number', models.IntegerField()),
            ],
        ),
    ]
