# Generated by Django 5.0.4 on 2024-04-25 04:47

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('date_of_birth', models.DateField()),
                ('address_street', models.CharField(max_length=80)),
                ('address_number', models.IntegerField()),
                ('registration_number', models.IntegerField(null=True)),
                ('is_principal', models.BooleanField(null=True)),
                ('is_employee', models.CharField(null=True)),
                ('is_student', models.CharField(null=True)),
                ('updated_at', models.DateField(null=True)),
                ('created_at', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
