# Generated by Django 5.0.4 on 2024-04-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='updated_at',
        ),
    ]
