# Generated by Django 5.0.4 on 2024-04-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app_api', '0002_remove_student_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
